name: 'Setup PHP Project'
description: 'Setup PHP with Composer caching and dependency installation'
author: 'PDF Content Search Team'

inputs:
  php-version:
    description: 'PHP version to use'
    required: false
    default: '8.4'
  extensions:
    description: 'PHP extensions to install (comma-separated)'
    required: false
    default: 'ctype, iconv'
  tools:
    description: 'Tools to install (e.g., composer:v2)'
    required: false
    default: 'composer:v2'
  install-dependencies:
    description: 'Whether to run composer install'
    required: false
    default: 'true'
  coverage:
    description: 'Code coverage driver (none, xdebug, pcov)'
    required: false
    default: 'none'

runs:
  using: 'composite'
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 # v2.31.1
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.extensions }}
        coverage: ${{ inputs.coverage }}
        tools: ${{ inputs.tools }}

    - name: Get Composer cache directory
      id: composer-cache
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache Composer dependencies
      uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      run: composer install --prefer-dist --no-progress --no-interaction
