<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Doctrine\Set\DoctrineSetList;
use Rector\Set\ValueObject\SetList;
use Rector\Symfony\Set\SymfonySetList;

return RectorConfig::configure()
    ->withPaths([
        __DIR__ . '/src',
        __DIR__ . '/tests',
    ])
    ->withSkip([
        // Auto-generated by Symfony — never touch
        __DIR__ . '/src/Kernel.php',
    ])

    // ----------------------------------------------------------------
    // PHP 8.4 — apply all improvements up to and including PHP 8.4:
    //   readonly properties, intersection types, fibers, enums,
    //   match expressions, nullsafe operator, named arguments, etc.
    //   Already required in composer.json (>=8.4), so this is safe.
    // ----------------------------------------------------------------
    ->withPhpSets(php84: true)

    ->withSets([
        // ----------------------------------------------------------------
        // PHP General Quality
        // ----------------------------------------------------------------

        // Simplify conditions, remove useless casts, null comparisons,
        // sprintf → string interpolation where trivial, etc.
        SetList::CODE_QUALITY,

        // Remove dead code: unreachable statements, unused private methods,
        // assignments whose value is never read, etc.
        // Complements the manual dead-code cleanup already done.
        SetList::DEAD_CODE,

        // Add missing return/param/property type hints.
        // Pairs with PHPStan level 8 — Rector fills gaps automatically.
        SetList::TYPE_DECLARATION,

        // Refactor deeply nested if/else to early returns.
        // Consistent with the guard-clause pattern already used in the codebase.
        SetList::EARLY_RETURN,

        // Improve instanceof usage: remove redundant checks, replace
        // get_class() === X comparisons with instanceof, etc.
        SetList::INSTANCEOF,

        // NOTE: SetList::CODING_STYLE is intentionally omitted.
        //       PHP-CS-Fixer handles all style concerns — running both
        //       would produce conflicts and duplicated effort.

        // NOTE: SetList::NAMING is intentionally omitted.
        //       Rename rules are too opinionated and disruptive;
        //       review naming changes manually.

        // ----------------------------------------------------------------
        // Symfony 7.4
        // ----------------------------------------------------------------

        // Symfony-version-specific rectors: deprecation fixes,
        // upgraded APIs, removed/renamed classes for SF 7.4.
        SymfonySetList::SYMFONY_74,

        // Symfony best practices: ResponseHeaderBag constants,
        // Request::isMethodIdempotent, etc.
        SymfonySetList::SYMFONY_CODE_QUALITY,

        // Ensure dependencies are injected via constructor rather than
        // fetched from the container — enforces the DI pattern already
        // used throughout this project.
        SymfonySetList::SYMFONY_CONSTRUCTOR_INJECTION,

        // ----------------------------------------------------------------
        // Doctrine ORM 3.x / DBAL 4.x
        // NOTE: DOCTRINE_ANNOTATIONS_TO_ATTRIBUTES omitted — all mappings
        //       already use PHP 8 attributes (#[ORM\Entity], etc.).
        // ----------------------------------------------------------------

        // Best-practice improvements: direct use of EntityManager,
        // repository method patterns, etc. Safe for ORM 3.x.
        DoctrineSetList::DOCTRINE_CODE_QUALITY,
    ]);
