<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251210145610 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create search_analytics table for tracking search queries and user behavior';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE search_analytics (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, session_id VARCHAR(64) NOT NULL, query TEXT NOT NULL, search_strategy VARCHAR(20) NOT NULL, results_count INT NOT NULL, response_time_ms INT NOT NULL, clicked BOOLEAN NOT NULL, clicked_position INT DEFAULT NULL, clicked_pdf VARCHAR(255) DEFAULT NULL, clicked_page INT DEFAULT NULL, time_to_click_ms INT DEFAULT NULL, user_ip VARCHAR(45) DEFAULT NULL, user_agent TEXT DEFAULT NULL, referer TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_created_at ON search_analytics (created_at)');
        $this->addSql('CREATE INDEX idx_session ON search_analytics (session_id)');
        $this->addSql('CREATE INDEX idx_clicked ON search_analytics (clicked)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE search_analytics');
    }
}
